name: Release

on:
  workflow_dispatch:
    inputs:
      commit:
        description: Branch, tag or commit hash
        type: string
        default: main
      default-bump:
        description: Default version bump (if none found in commit messages)
        type: choice
        options:
          - major
          - minor
          - patch
        default: patch

permissions:
  contents: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit }}

      - name: Create tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ github.event.inputs.default-bump }}
          create_annotated_tag: true

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.new_tag }}
          name: ${{ steps.tag.outputs.new_tag }}
          generateReleaseNotes: true
